name: pw6 gof autotests
# Когда запускаем
on: 
  push:
    branches:
      - main
# Ручной запуск (должно быть на одном уровне с push)
  workflow_dispatch:

jobs:
  pw6tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
      - name: Устанавливаем пакеты с package.json
        run: npm ci
      - name: Устанавливаем браузеры
        run: npx playwright install --with-deps
      - name: Запуст тестов
        run: npx playwright test
      - name: Генерация Allure отчета
        run: npx allure awesome ./allure-results --single-file
        # Если генерация отчета упадет, Workflow продолжит выполнение.
        continue-on-error: true
        # Выполнять этот шаг всегда
        if: always()
# Загрузить файл(ы) как артефакт GitHub Actions,Это файлы, которые GitHub сохранит после завершения workflow.
#allure-report, playwright-report, screenshots, videos, logs...
      - name: Upload test artifacts
        uses: actions/upload-artifact@v7.0.1
        # Если генерация отчета упадет, Workflow продолжит выполнение.
        continue-on-error: true
        # Выполнять этот шаг всегда
        if: always()
        with:
          name: test-artifacts
          path: |
            allure-report
            playwright-report
